version: "3"

services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: on-failure
    
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - app
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/app/static
    ports:
      - "127.0.0.1:8000:8000"

  app:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py collectstatic --no-input; python3 manage.py migrate; uvicorn mysite.asgi:application --port 8000 --host 0.0.0.0 '
    volumes:
      - static:/app/static
      - .:/app/
    depends_on:
      - db
    restart: on-failure


volumes:
  postgresql-data:
  static: